version: '3'
services:
  socket:
    platform: linux/amd64
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: socket_test
    ports:
      - "5555:5555"
    volumes:
      - ./app:/app  # <<=== Agrega esto para montar tu código local
    networks:
      - mi-red
networks:
  mi-red:
    driver: bridge